spring:
  cloud:
    kubernetes:
      config:
        name: app1
        sources:
          - namespace: shared
            name: shared
      configuration:
        watcher:
          actuatorPath: /actuator
          actuatorPort: 8081
  application:
    name: app1
server:
  port: 8081
app:
  message: Base Message from the app
  timeout: 1000
  shared: Shared Message from app
shared:
  toggleA: DHG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
logging:
  config:

