apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app2.name" . }}
  labels:
    {{- include "app2.labels" . | nindent 4 }}
data:
  application.properties: |-
    app.message=Overriden Message from Configmap
    app.timeout=500