apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app1.name" . }}
  labels:
    {{- include "app1.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "app1.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app1.name" . }}