apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.server.fullname" . }}
data:
  application.properties: |-
    spring.cloud.stream.kafka.binder.brokers={{ .Release.Name }}-kafka-0.{{ .Release.Name }}-kafka-headless.default.svc.cluster.local
  bootstrap.properties: |-
    spring.application.name={{include "config.server.fullname" . }}