apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.client.fullname" . }}
data:
  application.properties: |-
    spring.cloud.stream.kafka.binder.brokers={{ .Release.Name }}-kafka.default.svc.cluster.local
    spring.cloud.bus.id={{include "config.client.fullname" . }}:dev
  bootstrap.properties: |-
    spring.cloud.config.uri=http://{{ include "config.server.fullname" . }}:8888
    spring.application.name={{include "config.client.fullname" . }}
    spring.profiles.active=dev