apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "configwithspringcloud.name" . }}
  labels:
    {{- include "configwithspringcloud.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","configmaps","endpoints","services"]
    verbs: ["get", "watch", "list"]