apiVersion: v1
kind: Service
metadata:
  name: {{ include "config.server.fullname" . }}
  labels:
    {{- include "configwithspringcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "configwithspringcloud.selectorLabels" . | nindent 4 }}
