apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spring-sample-app.name" . }}
  labels:
    {{- include "spring-sample-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spring-sample-app.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spring-sample-app.name" . }}